processor_spec:
  to_dict:
    - "My name is {name} and I'm {age:d} years old."

  to_format:
    "Her name is {name} and she's {age:d} years old.":
      name_line: "Name is {name}"
      age_line: "Age is {age:d}"

port: 8888
address : '0.0.0.0'

indexer_config:
  host: localhost
  port: 9200
  index_pattern: 'kita-indexer-%Y-%m'

logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    default:
      format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
  handlers:
    default:
      class: logging.StreamHandler
      formatter: default
      stream: ext://sys.stdout
      level: INFO
  root:
    handlers:
      - default
    level: INFO
